# Import standard packages
import json
from typing import Any, Optional

# Import third-party packages
from firebase_admin import firestore
from google.cloud.firestore import Client, CollectionReference, DocumentReference, Query, SERVER_TIMESTAMP

# Import custom modules
from src.raphael.agentry.screenplay_breakdown.models import Screenplay
from src.raphael.auth import firebase_app
from src.raphael.history.models import PackedReport, Project, ProjectSummary
from src.raphael.history.serialization import pack_report, unpack_report
from src.raphael.recommendation.models import RecommendationReport


# Firestore rejects any document over 1 MiB. Budget below that: the ceiling
# counts Firestore's own field-name and index overhead, which this JSON
# estimate doesn't, and hitting it surfaces as an opaque 400 from the API
# rather than anything a caller could act on.
_DOCUMENT_SIZE_BUDGET = 900_000


class ProjectNotFoundError(Exception):
    """Raised when a project id doesn't exist under the given uid -- wrong id, or someone else's."""


class ReportTooLargeError(Exception):
    """Raised when a packed report would exceed Firestore's per-document ceiling."""


def _document_size(payload: dict[str, Any]) -> int:
    """
    Approximate stored size of a document, as the byte length of its JSON.
    """
    return len(json.dumps(payload, default=str).encode("utf-8"))


def _to_summary(snapshot: Any) -> ProjectSummary:
    """
    Builds a history-list row from a project snapshot, without touching its
    reports subcollection.
    """
    data = snapshot.to_dict() or {}
    return ProjectSummary(
        id=snapshot.id,
        title=data.get("title", "Untitled"),
        character_count=data.get("character_count", 0),
        has_report=data.get("latest_report_id") is not None,
        created_at=data.get("created_at"),
        updated_at=data.get("updated_at"),
    )


def _to_project(snapshot: Any, latest_report: Optional[RecommendationReport]) -> Project:
    """
    Builds a full Project from a project snapshot and its already-rehydrated
    latest report (None if it has none yet).
    """
    data = snapshot.to_dict() or {}
    return Project(
        id=snapshot.id,
        title=data.get("title", "Untitled"),
        screenplay=Screenplay.model_validate(data["screenplay"]),
        latest_report=latest_report,
        created_at=data.get("created_at"),
        updated_at=data.get("updated_at"),
    )


class HistoryStore:
    """
    Per-user persistence for screenplays and their recommendation reports,
    backed by Cloud Firestore. Every path is rooted at users/{uid}, so a
    caller can only ever reach the history of the uid it passes in.
    """

    # Every method here is deliberately sync, and every route that calls one
    # is declared `def` so FastAPI runs it in a threadpool -- same convention,
    # for the same reason, as auth.verify_token. The async Firestore client is
    # the alternative, but firestore_async.client() caches one AsyncClient per
    # app forever and its gRPC channel binds to whichever event loop built it,
    # so it breaks the moment anything touches the store from a second loop
    # (a test client, a startup task, a CLI like etl/populate.py). Firestore
    # round trips are short I/O; the threadpool hop is the cheaper trade.

    @property
    def client(self) -> Client:
        """
        Returns the process-wide Firestore client, connecting on first use.
        """

        # Lazy for the same reason firebase_app() is: importing this module
        # must never require credentials, only touching Firestore does.
        # firebase_admin caches the client on the app, so this is not a
        # per-call connection.
        return firestore.client(app=firebase_app())

    def _projects(self, uid: str) -> CollectionReference:
        """
        The projects collection for one user.
        """
        return self.client.collection("users").document(uid).collection("projects")

    def _project(self, uid: str, project_id: str) -> DocumentReference:
        """
        One user's project document.
        """
        return self._projects(uid).document(project_id)

    def create_project(self, uid: str, screenplay: Screenplay) -> Project:
        """
        Stores a new project holding `screenplay`, returning it with the
        generated id. The id is generated by Firestore rather than derived
        from the title, which is neither unique nor stable across edits.
        """
        document = self._projects(uid).document()
        document.set(
            {
                "title": screenplay.title,
                "screenplay": screenplay.model_dump(mode="json"),
                "character_count": len(screenplay.cast.characters),
                "latest_report_id": None,
                "created_at": SERVER_TIMESTAMP,
                "updated_at": SERVER_TIMESTAMP,
            },
        )

        # Read back so the caller gets resolved server timestamps rather than
        # the sentinel, and so ordering is decided by Firestore's clock.
        return _to_project(document.get(), latest_report=None)

    def list_projects(self, uid: str, limit: int = 50) -> list[ProjectSummary]:
        """
        Returns one user's projects, most recently touched first. Reads only
        the project documents -- never the reports underneath them.
        """
        query = self._projects(uid).order_by("updated_at", direction=Query.DESCENDING).limit(limit)
        return [_to_summary(snapshot) for snapshot in query.stream()]

    def get_project(self, uid: str, project_id: str) -> Optional[Project]:
        """
        Returns one project with its latest report rehydrated, or None if no
        such project exists for this user.
        """
        snapshot = self._project(uid, project_id).get()
        if not snapshot.exists:
            return None

        latest_report_id = (snapshot.to_dict() or {}).get("latest_report_id")
        latest_report = None
        if latest_report_id is not None:
            latest_report = self.get_report(uid, project_id, latest_report_id)

        return _to_project(snapshot, latest_report)

    def get_report(self, uid: str, project_id: str, report_id: str) -> Optional[RecommendationReport]:
        """
        Reads one stored report and puts its deduplicated dossiers back on the
        candidates they came off, returning None if it doesn't exist.
        """
        snapshot = self._project(uid, project_id).collection("reports").document(report_id).get()
        if not snapshot.exists:
            return None
        return unpack_report(PackedReport.model_validate(snapshot.to_dict()))

    def ensure_project_exists(self, uid: str, project_id: str) -> None:
        """
        Raises ProjectNotFoundError unless `project_id` exists for this user.
        Lets a caller reject a bad id up front instead of after running the
        pipeline (see app.recommend).
        """
        if not self._project(uid, project_id).get().exists:
            raise ProjectNotFoundError(project_id)

    def save_report(self, uid: str, project_id: str, report: RecommendationReport) -> str:
        """
        Stores a report against an existing project and marks it the latest,
        returning the new report's id. Raises ProjectNotFoundError for an
        unknown id, ReportTooLargeError if it won't fit in a document.
        """
        project = self._project(uid, project_id)
        if not project.get().exists:
            raise ProjectNotFoundError(project_id)

        payload = pack_report(report).model_dump(mode="json")
        size = _document_size(payload)
        if size > _DOCUMENT_SIZE_BUDGET:
            raise ReportTooLargeError(
                f"Report is ~{size} bytes packed, over the {_DOCUMENT_SIZE_BUDGET} byte budget.",
            )

        # Batched so the report and the pointer to it land together -- writing
        # them separately can leave a stored report the project never
        # references, which nothing would ever read or clean up.
        document = project.collection("reports").document()
        batch = self.client.batch()
        batch.set(document, {**payload, "created_at": SERVER_TIMESTAMP})
        batch.update(project, {"latest_report_id": document.id, "updated_at": SERVER_TIMESTAMP})
        batch.commit()

        return document.id

    def delete_project(self, uid: str, project_id: str) -> bool:
        """
        Deletes a project and every report under it, returning False if there
        was no such project for this user.
        """
        project = self._project(uid, project_id)
        if not project.get().exists:
            return False

        # Deleting a document does NOT delete its subcollections -- without
        # this the reports would be orphaned but still billed and readable by
        # id. One batch is enough at this scale: a project accumulates one
        # report per /recommend run, far short of the 500-op batch limit.
        batch = self.client.batch()
        for report in project.collection("reports").list_documents():
            batch.delete(report)
        batch.delete(project)
        batch.commit()

        return True
